-- Images are stored in Supabase Storage bucket product-images.
-- Re-upload with: python3 supabase/upload-pics.py

insert into public.products (name, model, storage, price, description, category, image, stock, featured, colors) values
('iPhone 17', 'iPhone 17', '128GB', 1100.00, 'The newest iPhone featuring the most advanced A19 chip, an all-new design, enhanced camera system with Apple Intelligence, and an all-day battery.', 'iphones', '/Pics/IPhone 17.jpg', 25, true, 'Black,White,Blue,Green,Pink'),
('iPhone 17 Pro', 'iPhone 17 Pro', '256GB', 1700.00, 'Pro-level performance with A19 Pro chip, titanium design, revolutionary 48MP camera system with tetraprism lens, and the most advanced display ever.', 'iphones', '/Pics/iphone 17pro.jpg', 15, true, 'Black Titanium,White Titanium,Blue Titanium'),
('iPhone 17 Pro Max', 'iPhone 17 Pro Max', '256GB', 1750.00, 'The most advanced iPhone ever. A19 Pro chip, titanium design, groundbreaking camera system, largest display, and all-day battery life.', 'iphones', '/Pics/iphone 17pro max.jpg', 12, true, 'Black Titanium,White Titanium,Blue Titanium'),
('iPhone 16', 'iPhone 16', '128GB', 820.00, 'Built for Apple Intelligence with A18 chip, 48MP Fusion camera, Camera Control, Action button, and a vibrant 6.1-inch display.', 'iphones', '/Pics/iPhone 16.jpg', 20, false, 'Black,White,Pink,Teal,Ultramarine'),
('iPhone 16 Plus', 'iPhone 16 Plus', '256GB', 1150.00, 'The larger 6.7-inch display with Apple Intelligence, A18 chip, 48MP Fusion camera, Camera Control, and Action button.', 'iphones', '/Pics/iphone16  plus.jpg', 12, false, 'Black,White,Pink,Teal,Ultramarine'),
('iPhone 16 Pro Max', 'iPhone 16 Pro Max', '256GB', 1250.00, 'The ultimate iPhone with titanium design, A18 Pro chip, 48MP Fusion camera with 5x optical zoom, Camera Control, and stunning 6.9-inch display.', 'iphones', '/Pics/iphone 16 pro.jpg', 8, false, 'Desert Titanium,Natural Titanium,White Titanium,Black Titanium'),
('iPhone 15', 'iPhone 15', '128GB', 700.00, 'Dynamic Island, 48MP camera system, A16 Bionic chip, USB-C, and Ceramic Shield. A bright 6.1-inch Super Retina XDR display.', 'iphones', '/Pics/iphone15.jpg', 20, false, 'Black,Blue,Green,Yellow,Pink'),
('iPhone 15 Plus', 'iPhone 15 Plus', '128GB', 750.00, 'The bigger 6.7-inch display with Dynamic Island, 48MP camera, A16 Bionic chip, and USB-C connector.', 'iphones', '/Pics/iphone15 plus.jpg', 15, false, 'Black,Blue,Green,Yellow,Pink'),
('iPhone 15 Pro', 'iPhone 15 Pro', '256GB', 790.00, 'Titanium design, A17 Pro chip, customizable Action button, 48MP camera system with 3x optical zoom, USB-C with USB 3 speeds.', 'iphones', '/Pics/iphone 15 pro.jpg', 12, false, 'Natural Titanium,Blue Titanium,White Titanium,Black Titanium'),
('iPhone 15 Pro Max', 'iPhone 15 Pro Max', '256GB', 890.00, 'The most powerful iPhone with titanium design, A17 Pro chip, 5x optical zoom, USB-C with USB 3 speeds, and all-day battery life.', 'iphones', '/Pics/iphone 15 pro max.jpg', 10, false, 'Natural Titanium,Blue Titanium,White Titanium,Black Titanium'),
('iPhone 14', 'iPhone 14', '128GB', 520.00, '6.1-inch Super Retina XDR display, A15 Bionic chip, advanced camera system with Photographic Styles, and crash detection.', 'iphones', '/Pics/iphone14.jpg', 18, false, 'Midnight,Starlight,Blue,Purple,Red'),
('iPhone 14 Plus', 'iPhone 14 Plus', '128GB', 630.00, 'The bigger 6.7-inch display with all the amazing features of iPhone 14 including A15 Bionic chip and advanced camera system.', 'iphones', '/Pics/iphone 14 plus.webp', 12, false, 'Midnight,Starlight,Blue,Purple,Red'),
('iPhone 14 Pro', 'iPhone 14 Pro', '128GB', 650.00, 'Pro motion display with Always-On and Dynamic Island, A16 Bionic chip, 48MP main camera, and all-day battery life.', 'iphones', '/Pics/iphone 14 pro.jpg', 10, false, 'Deep Purple,Gold,Silver,Space Black'),
('iPhone 14 Pro Max', 'iPhone 14 Pro Max', '128GB', 690.00, 'The most advanced iPhone with Dynamic Island, Always-On display, A16 Bionic chip, 48MP camera system, and all-day battery life.', 'iphones', '/Pics/iphone 14 pro max.webp', 8, false, 'Deep Purple,Gold,Silver,Space Black'),
('iPhone 14 Pro Max', 'iPhone 14 Pro Max', '256GB', 720.00, 'The most advanced iPhone with Dynamic Island, Always-On display, A16 Bionic chip, 48MP camera system, and all-day battery life.', 'iphones', '/Pics/iphone 14 pro max.webp', 6, false, 'Deep Purple,Gold,Silver,Space Black'),
('iPhone 13', 'iPhone 13', '128GB', 490.00, 'A15 Bionic chip, 6.1-inch Super Retina XDR display with Ceramic Shield, advanced dual-camera system with sensor-shift optical image stabilization.', 'iphones', '/Pics/iphone 13.avif', 16, false, 'Pink,Blue,Midnight,Starlight,Red'),
('iPhone 13', 'iPhone 13', '256GB', 520.00, 'A15 Bionic chip, 6.1-inch Super Retina XDR display with Ceramic Shield, advanced dual-camera system with sensor-shift optical image stabilization.', 'iphones', '/Pics/iphone 13.avif', 12, false, 'Pink,Blue,Midnight,Starlight,Red'),
('iPhone 13 Pro', 'iPhone 13 Pro', '128GB', 570.00, 'Super Retina XDR display with ProMotion, A15 Bionic chip with 5-core GPU, pro camera system, and all-day battery life.', 'iphones', '/Pics/iphone 13 pr.webp', 10, false, 'Sierra Blue,Graphite,Gold,Silver,Alpine Green'),
('iPhone 13 Pro Max', 'iPhone 13 Pro Max', '128GB', 590.00, 'The most capable iPhone ever with 6.7-inch Super Retina XDR display with ProMotion, A15 Bionic chip, and advanced pro camera system.', 'iphones', '/Pics/iphone 13 pro max.jpg', 8, false, 'Sierra Blue,Graphite,Gold,Silver,Alpine Green'),
('iPhone 13 Pro Max', 'iPhone 13 Pro Max', '256GB', 620.00, 'The most capable iPhone ever with 6.7-inch Super Retina XDR display with ProMotion, A15 Bionic chip, and advanced pro camera system.', 'iphones', '/Pics/iphone 13 pro max 256gb.jpg', 7, false, 'Sierra Blue,Graphite,Gold,Silver,Alpine Green'),
('iPhone 12', 'iPhone 12', '128GB', 380.00, 'Beautifully bright 6.1-inch Super Retina XDR display with Ceramic Shield, A14 Bionic chip, and advanced dual-camera system.', 'iphones', '/Pics/iphone12.jpg', 14, false, 'Black,White,Green,Blue,Red'),
('iPhone 12 Pro', 'iPhone 12 Pro', '128GB', 430.00, 'Pro-level performance with A14 Bionic, 6.1-inch Super Retina XDR display, pro camera system with LiDAR Scanner.', 'iphones', '/Pics/iphone 12 pro.avif', 10, false, 'Gold,Pacific Blue,Graphite,Silver'),
('iPhone 12 Pro Max', 'iPhone 12 Pro Max', '128GB', 480.00, 'The biggest display ever on iPhone at 6.7 inches. A14 Bionic chip, advanced pro camera system, and LiDAR Scanner.', 'iphones', '/Pics/iphone 12 pro max.webp', 8, false, 'Gold,Pacific Blue,Graphite,Silver'),
('iPhone 12 Pro Max', 'iPhone 12 Pro Max', '256GB', 520.00, 'The biggest display ever on iPhone at 6.7 inches. A14 Bionic chip, advanced pro camera system, and LiDAR Scanner.', 'iphones', '/Pics/iphone 12 pro max 256gb.avif', 6, false, 'Gold,Pacific Blue,Graphite,Silver'),
('iPhone 11', 'iPhone 11', '64GB', 300.00, 'Experience the power of the A13 Bionic chip with iPhone 11. Features a stunning 6.1-inch Liquid Retina HD display, dual-camera system, and all-day battery life.', 'iphones', '/Pics/iphone11.jpg', 15, false, 'Black,White,Green,Red,Purple,Yellow'),
('iPhone 11', 'iPhone 11', '128GB', 330.00, 'Experience the power of the A13 Bionic chip with iPhone 11. Features a stunning 6.1-inch Liquid Retina HD display, dual-camera system, and all-day battery life.', 'iphones', '/Pics/iphone11.jpg', 12, false, 'Black,White,Green,Red,Purple,Yellow'),
('iPhone 11 Pro Max', 'iPhone 11 Pro Max', '256GB', 390.00, 'The most powerful iPhone with a 6.5-inch Super Retina XDR display, triple-camera system, and A13 Bionic chip for extraordinary performance.', 'iphones', '/Pics/iphone 11 pro max.png', 8, false, 'Gold,Space Gray,Silver,Green,Purple');

insert into public.products (name, model, storage, price, description, category, image, stock, featured, colors) values
('AirPods Pro 2', 'AirPods Pro', 'N/A', 249.00, 'Active Noise Cancellation, Adaptive Transparency, Personalized Spatial Audio. Up to 6 hours of listening time.', 'accessories', '/Pics/airpods pro2.jpg', 25, false, 'White'),
('AirPods 4', 'AirPods', 'N/A', 129.00, 'Apple AirPods 4 with Apple-designed H2 chip, personalized Spatial Audio, and up to 30 hours total listening time with charging case.', 'accessories', '/Pics/airpods pro4.webp', 30, false, 'White'),
('Apple Watch Series 10', 'Apple Watch', '42mm', 399.00, 'Thinnest Apple ever. Faster S10 chip, wider display, sleep apnea detection, water temperature sensor, and up to 18 hours of battery life.', 'accessories', '/Pics/apple watch series 10.jpg', 15, false, 'Midnight,Starlight,Silver'),
('Apple Watch Ultra 2', 'Apple Watch Ultra', '49mm', 799.00, 'The most rugged Apple Watch. 49mm titanium case, precision dual-frequency GPS, up to 36 hours of battery life.', 'accessories', '/Pics/apple watch ultra 2.webp', 8, false, 'Natural Titanium,Black Titanium'),
('iPhone 17 Clear Case', 'Case', 'N/A', 49.00, 'Designed by Apple for iPhone 17. Slim, clear design that shows off your iPhone while protecting it.', 'accessories', '/Pics/IPhone 17.jpg', 50, false, 'Clear'),
('20W USB-C Power Adapter', 'Charger', 'N/A', 19.00, 'Apple 20W USB-C power adapter for fast and efficient charging of your iPhone.', 'accessories', '/Pics/adapter.webp', 100, false, 'White'),
('USB-C to USB-C Cable (1m)', 'Cable', 'N/A', 15.00, 'Apple USB-C to USB-C charging cable. Durable woven design.', 'accessories', '/Pics/usb cable.webp', 80, false, 'White'),
('2TB iCloud Storage', 'iCloud', '2TB', 9.99, 'iCloud+ with 2TB storage. Securely store all your photos, files, and more.', 'accessories', '/Pics/2tb icloud storage.jpg', 999, false, 'N/A');

insert into public.products (name, model, storage, price, price_label, description, category, image, stock, featured, colors) values
('Tempered Glass', 'Tempered Glass', 'N/A', 5.00, 'From $5', 'Scratch-resistant screen protection for your device. From $5 - $15.', 'accessories', '/Pics/tempered glass.webp', 25, false, 'Clear'),
('Camera Lens Protector', 'Camera Lens Protector', 'N/A', 10.00, null, 'Protective coverage for your phone camera lenses.', 'accessories', '/Pics/camera lens .webp', 25, false, 'Clear'),
('Fast Charger', 'Fast Charger', 'N/A', 15.00, null, 'Fast, reliable charging for compatible devices.', 'accessories', '/Pics/fast charger .webp', 25, false, 'White'),
('Samsung Cases', 'Samsung Cases', 'N/A', 5.00, 'From $5', 'Protective cases designed for Samsung Galaxy devices. From $5 - $10.', 'accessories', '/Pics/samsung cases.webp', 25, false, 'Black,White'),
('iPhone Cases', 'iPhone Cases', 'N/A', 5.00, 'From $5', 'Slim protective cases for iPhone models. From $5 - $10.', 'accessories', '/Pics/iphone case.webp', 25, false, 'Black,White'),
('Headphones', 'Headphones', 'N/A', 25.00, null, 'Comfortable headphones for immersive everyday listening.', 'accessories', '/Pics/headphones.webp', 25, false, 'Black,White');

insert into public.products (name, model, storage, price, description, category, image, stock, featured, colors) values
('Samsung Galaxy S21 Ultra', 'Samsung Galaxy S21 Ultra', 'N/A', 300.00, 'A premium Galaxy flagship with a versatile camera system, vivid display, and powerful everyday performance.', 'samsung', '/Pics/S21 Ultra.webp', 10, false, 'Black,Silver'),
('Samsung Galaxy S22', 'Samsung Galaxy S22', 'N/A', 340.00, 'A compact Galaxy flagship with a bright display, capable camera system, and smooth performance.', 'samsung', '/Pics/s22.webp', 10, false, 'Black,White,Green'),
('Samsung Galaxy S22 Ultra', 'Samsung Galaxy S22 Ultra', 'N/A', 390.00, 'Galaxy Note-inspired flagship power with an integrated S Pen and an advanced camera experience.', 'samsung', '/Pics/s22 Ultra.webp', 10, false, 'Black,White,Green'),
('Samsung Galaxy S23', 'Samsung Galaxy S23', 'N/A', 450.00, 'A refined Galaxy flagship with fast performance, a crisp display, and a dependable camera system.', 'samsung', '/Pics/s23.webp', 10, false, 'Black,White,Green'),
('Samsung Galaxy S23 Ultra', 'Samsung Galaxy S23 Ultra', 'N/A', 549.00, 'Ultra-level Galaxy performance with an S Pen, high-resolution camera, and expansive display.', 'samsung', '/Pics/s23 ultra.jpg', 10, false, 'Black,White,Green'),
('Samsung Galaxy S24', 'Samsung Galaxy S24', 'N/A', 620.00, 'A modern Galaxy flagship with intelligent features, a bright display, and all-day capability.', 'samsung', '/Pics/s24.webp', 10, false, 'Black,Silver,Blue'),
('Samsung Galaxy S24 Ultra', 'Samsung Galaxy S24 Ultra', 'N/A', 699.00, 'Titanium-finished Galaxy Ultra performance with an S Pen and a pro-grade camera system.', 'samsung', '/Pics/s24 ultra.webp', 10, false, 'Black,Silver,Blue'),
('Samsung Galaxy S25', 'Samsung Galaxy S25', 'N/A', 720.00, 'The next-generation Galaxy flagship, designed for fast performance and intelligent everyday use.', 'samsung', '/Pics/s25.webp', 10, false, 'Black,Silver,Blue'),
('Samsung Galaxy S25 Ultra', 'Samsung Galaxy S25 Ultra', 'N/A', 899.00, 'A premium Galaxy Ultra with exceptional performance, a versatile camera, and a spacious display.', 'samsung', '/Pics/s25 ultra.webp', 10, false, 'Black,Silver,Blue'),
('Samsung Galaxy S26', 'Samsung Galaxy S26', 'N/A', 950.00, 'The latest Galaxy flagship with advanced performance, a polished design, and a vivid display.', 'samsung', '/Pics/s26.webp', 10, false, 'Black,Silver,Blue'),
('Samsung Galaxy S26 Ultra', 'Samsung Galaxy S26 Ultra', 'N/A', 1299.00, 'The ultimate Galaxy experience with flagship performance, pro-grade imaging, and an immersive display.', 'samsung', '/Pics/s26 ultra.webp', 10, false, 'Black,Silver,Blue');
